### ISSUE TITLE
no main manifest attribute, in ic3-android.jar

### ISSUE THREAD

**Issue by Mohannadcse** [dialdroid-android/ic3-dialdroid#1]
I tried to run ic3-android according to the provided steps, but received the following error `no main manifest attribute, in ic3-android.jar`, where I tried ic3-android.jar exists in the ic3-android directory and the build directory.
So can you please advise me how to overcome this issue.

**Comment by amiangshu** [comment]
You have run the ic3-dialdroid.jar (not ic3-android.jar), which is located inside the build directory.
