### ISSUE TITLE
`Error computing SHA of apk file!`

### ISSUE THREAD

**Issue by shengliangd** [dialdroid-android/ic3-dialdroid#3]
I'm trying to use ic3-dialdroid to generate ICC models of apps. I tried several apps including shadowsocks and telegram, however, it always shows `Error computing SHA of apk file!` and then exit. Are there mistakes in my command(I tried both of them with relative and absolute paths):

1. `java -Xmx4g -jar build/ic3-dialdroid.jar -in <path-to-my-apk> -cp <path-to->`
2. `java -Xmx4g -jar build/ic3-dialdroid.jar -input <path-to-my-apk> -cp <path-to->`

**Comment by MateoVakili** [comment]
I'm having the same problem here. Any ideas how to fix this ?

**Comment by amiangshu** [comment]
You need to use java 1.8. Recent versions of Java has disabled several crypto related APIs.
